apiVersion: v1
kind: Secret
metadata:
  name: private-repo-apps
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:1mbili/K8s-inzynierka-apps.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACD3aBSwRep4/PWHboTHzd8Qwp8+q0zEjUJDRlJgBgYFsQAAAJjaU5C+2lOQ
    vgAAAAtzc2gtZWQyNTUxOQAAACD3aBSwRep4/PWHboTHzd8Qwp8+q0zEjUJDRlJgBgYFsQ
    AAAECWxrsCJVHWa1DA4RHaUlmGSLBbrvFYBOuvLkAw7c1fGvdoFLBF6nj89YduhMfN3xDC
    nz6rTMSNQkNGUmAGBgWxAAAAFGJpbHVAREVTS1RPUC1PRjhORUdRAQ==
    -----END OPENSSH PRIVATE KEY-----
