apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aes-key
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-backend
  target:
    name: aes-key
    creationPolicy: Owner
  data:
    - secretKey: aes-key
      remoteRef:
        key: secret/AES-KEY
