apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aplikacja-inzynierka
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-backend
  data:
    - secretKey: tls.crt
      remoteRef:
        key: secret/cert
    - secretKey: tls.key
      remoteRef:
        key: secret/cert-key
