apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flask-secret-key
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-backend
  target:
    name: flask-secret-key
    creationPolicy: Owner
  data:
    - secretKey: flask-secret-key
      remoteRef:
        key: secret/FLASK-SECRET-KEY
