apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gmail-pass
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-backend
  target:
    name: gmail-pass
    creationPolicy: Owner
  data:
    - secretKey: gmail-pass
      remoteRef:
        key: secret/GMAIL-PASS
