apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-user
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-backend
  target:
    name: mysql-user
    creationPolicy: Owner
  data:
    - secretKey: mysql-user
      remoteRef:
        key: secret/mysql-user
