apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pepper
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-backend
  target:
    name: pepper
    creationPolicy: Owner
  data:
    - secretKey: pepper
      remoteRef:
        key: secret/PEPPER
