apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-backend
spec:
  provider:
    azurekv:
      tenantId: 387de0e5-8207-47f6-8b78-73c97e396ade
      vaultUrl: "https://vault0a.vault.azure.net"
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: ClientID
          namespace: default
        clientSecret:
          name: azure-secret-sp
          key: ClientSecret
          namespace: default
