---
name: Integration
on:
  pull_request:
    branches:
      - main

jobs:
  Lint_Terraform:
    name: Lint Terraform
    runs-on: ubuntu-latest
    environment: PROD
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
          tflint_version: v0.44.1
      
      - name: Init TFLint
        run: tflint --init
    
      - name: Run TFLint
        run: tflint

  Plan_Terraform:
    name: Plan Terraform
    runs-on: ubuntu-latest
    environment: PROD
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        name: Setup terraform
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate
      
      - name: Terraform Plan
        run: terraform plan
        continue-on-error: true
      