---
name: Integration
on:
  pull_request:
    branches:
      - main

jobs:
  Deploy-Infrastructure:
    name: CI pipeline
    runs-on: ubuntu-latest
    environment: PROD
    defaults:
      run:
        working-directory: ./terraform
    steps:
    - name: Check out the codebase.
      uses: actions/checkout@v4
              
    