---
name: Integration
on:
  pull_request:
    branches:
      - main

jobs:
  Deploy-Infrastructure:
    name: CI pipeline
    runs-on: ubuntu-latest
    environment: PROD
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
          tflint_version: v0.44.1
      
      - name: Init TFLint
        run: tflint --init
    
      - name: Run TFLint
        run: tflint

