---
name: CI
'on':
  push:
    branches:
      - main


jobs:
  Deploy-Infrastructure:
    name: Terraform
    runs-on: ubuntu-latest
    environment: PROD
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        name: Setup Terraform
        with:
          terraform_version: "1.6.3"
    
      - name: Initialize Terraform
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}

      - name: Run terraform apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}
