---
name: CI
'on':
  push:
    branches:
      - main


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
            tflint_version: v0.44.1
    
      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact
