---
name: CI
'on':
  push:
    branches:
      - main


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    environment: PROD
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Test using secret
        run: echo "$dummy"
        env:
          dummy: ${{ vars.DUPA }}

      - name: Check out the codebase.
        uses: actions/checkout@v4

      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
            tflint_version: v0.44.1
    
      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

      - name: Initialize Terraform
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Run terraform apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
